<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Document</title>
    </head>
    <body>
        <script>
            // 注意点：
            // * async函数返回一个 Promise 对象
            // * async函数的语法规则总体上比较简单，难点是错误处理机制。
            // * await命令后面是一个 Promise 对象(类promise对象ok)，返回该对象的结果
            // * 任何一个await语句后面的 Promise 对象变为reject状态，那么整个async函数都会中断执行。
            // * async函数不会阻塞代码，异步操作存入事件队列，但是同一个async函数内部的await会阻塞内部执行
            // * async函数执行的时候，一旦遇到await就会先返回，等到异步操作完成，再接着执行函数体内后面的语句。
            // * async函数内部return语句返回的值，会成为then方法回调函数的参数。
            // * async函数返回的 Promise 对象，必须等到内部所有await命令后面的 Promise 对象执行完，才会发生状态改变，除非遇到return语句或者抛出错误。
            // * await返回的是promise中传给resolve的参数（）
            // * await命令后面是一个 Promise 对象，返回该对象的结果。如果不是 Promise 对象，就直接返回对应的值。
            // * await命令后面的 Promise 对象如果变为reject状态，则reject的参数会被async函数的catch方法的回调函数接收到。
            // * 任何一个await语句后面的 Promise 对象变为reject状态，那么整个async函数都会中断执行。
            // * 希望前一个异步操作失败，也不要中断后面的异步操作,可以在await后面加catch,但是只对执行reject有效，别的报错无效
            // * 推荐在await后面加上catch避免reject阻塞代码
            // * 多个await命令后面的异步操作，如果不存在继发关系，最好让它们同时触发。promise.all()方法
            // * await命令只能用在async函数之中
            // * async 函数可以保留运行堆栈

            fn2 = () => {
                return new Promise(resolve => {
                    setTimeout(() => {
                        console.log('fn2');
                        resolve(5);
                    }, 2000);
                });
            };
            fn3 = () => {
                return new Promise((resolve, reject) => {
                    // setTimeout(() => {
                    console.log('fn3');
                    resolve(222);
                    // resolve('fn3');
                    // reject(888);
                    // throw new Error('出错了');
                    // }, 2000);
                });
            };
            fn4 = () => {
                return new Promise(resolve => {
                    setTimeout(() => {
                        console.log('fn4');
                        resolve('fn4');
                    }, 2000);
                });
            };

            fn1 = async () => {
                console.log(111);
                const fn21 = await fn2();
                const fn31 = await fn3();
                const fn41 = await fn4();
                const fn21 = fn2().then(v => v);
                const fn31 = fn3().then(v => v);
                // const fn41 = fn4().then(v => v);
                // .catch(error =>
                //     console.log('error: ', error)
                // );
                try {
                    const fn21 = await fn2();
                    const fn31 = await fn3();
                    console.log(333);
                    const fn41 = await fn4();
                } catch (error) {
                    console.log('error: ', error);
                }
                return fn21 + fn31 + fn41;
            };
            // const abc =
            // fn1()
            //     .then(v => {
            //         console.log('v: ', v);
            //     })
            //     .catch(error => {
            //         console.log('error: ', error);
            //     });
            // console.log('abc: ', abc);
            console.log(555);

            fn7 = async () => {
                await fn2();
            };
            fn7().then(v => console.log('v', v));

            const store = createStore(appState, stateChanger);
            store.subscribe(() => renderApp(store.getState()));

            
        </script>
    </body>
</html>
